services:
  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
