# Generated by Django 3.2.18 on 2023-04-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_message_forwarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='sticker', to='Site.stickercollection')),
            ],
        ),
    ]
