# Generated by Django 3.2.18 on 2023-04-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20230403_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='Site.room'),
        ),
    ]
