# Generated by Django 3.2.18 on 2023-04-19 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='liked',
            field=models.IntegerField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
        migrations.AddField(
            model_name='message',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
