# Generated by Django 3.2.18 on 2023-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_auto_20230419_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
