# Generated by Django 3.2.18 on 2023-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_alter_message_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stickercollection',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
