# Generated by Django 3.2.18 on 2023-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_auto_20230421_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomRoom',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
