# Generated by Django 3.2.18 on 2023-10-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20230423_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-id']},
        ),
    ]
